apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fuse-pipelines-fuse-sources
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
