# merge from
# . 'system:openshift:controller:build-config-change-controller'
# . system:image-builder, but with extra grants on builds.
# . pods  [create get list watch]
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mvn-build-config-change-controller
rules:
  - verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
    apiGroups:
      - ''
      - build.openshift.io
    resources:
      - buildconfigs
  - verbs:
      - create
    apiGroups:
      - ''
      - build.openshift.io
    resources:
      - buildconfigs/instantiate
  - verbs:
      - create
    apiGroups:
      - ''
      - build.openshift.io
    resources:
      - buildconfigs/instantiatebinary
  - verbs:
      - create
      - get 
      - list
      - patch 
      - update
      - watch
      - delete
    apiGroups:
      - ''
      - build.openshift.io
    resources:
      - builds
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - update
    apiGroups:
      - ''
      - image.openshift.io
    resources:
      - imagestreams/layers
  - verbs:
      - create
    apiGroups:
      - ''
      - image.openshift.io
    resources:
      - imagestreams
  - verbs:
      - update
    apiGroups:
      - ''
      - build.openshift.io
    resources:
      - builds/details
  - verbs:
      - create
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods/status
